version: "3.8"
services:
  proxy:
    build:
      context: .
      cache_from:
        - "docker.io/library/golang:1.13-alpine"
    image: devproxy2
    ports:
      - "8111:8111"
  nginx:
    image: "docker.io/library/nginx:latest"
