# Default configuration used by the Dockerfile.
[listen]
# Don't actually listen on 'localhost'.  It's a secure default for a host
# system, but in Docker, it prevents connections to the exposed port.
address = ""

[servers.local]
address = "nginx"

[[rules]]
match_host = '\bexample\.\w+$'
match_port = '^80$'
send_to = "local"
